### ISSUE TITLE
Bot crashes sporadically after some restarts

### ISSUE THREAD

**Issue by bemoty** [bemoty/botmoty#3]
get ur singletons right fool

```/home/bemoty/cbot/core/sorgen/SorgenHandler.js:16
            throw Error('SorgenHandler singleton already intialized!');
            ^
Error: SorgenHandler singleton already intialized!
    at new SorgenHandler (/home/bemoty/cbot/core/sorgen/SorgenHandler.js:16:19)
    at Client.<anonymous> (/home/bemoty/cbot/core/DiscordBot.js:39:17)
    at Client.emit (events.js:215:7)
    at WebSocketConnection.triggerReady (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at ReadyHandler.handle (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:79:8)
    at WebSocketPacketManager.handle (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/bemoty/cbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/bemoty/cbot/node_modules/ws/lib/event-target.js:120:16)```

**Comment by bemoty** [comment]
fixed in 22e5af5439e2bfccad377809598c2a99ee68e364
